### ISSUE TITLE
jasmine-2 branch throws `uninitialized constant Guard::Options (NameError)`

### ISSUE THREAD

**Issue by fifigyuri** [guard/guard-jasmine#182]
We've are using jasmine 2.0. I tried to use the branch `jasmine-2` (in `Gemfile` it's `gem 'guard-jasmine', github: 'guard/guard-jasmine', branch: 'jasmine-2'`), which I suppose is intended to work with jasmine 2.x. I get the following issue when I run `bundle exec guard-jasmine --server-timeout=180 --verbose`:

```
/Users/fifigyuri/Projects/projs/ui/vendor/bundle/ruby/2.2.0/gems/guard-2.10.5/lib/guard/ui.rb:40:in `options': uninitialized constant Guard::Options (NameError)
        from /Users/fifigyuri/Projects/projs/ui/vendor/bundle/ruby/2.2.0/gems/guard-2.10.5/lib/guard/ui.rb:171:in `_filter'
        from /Users/fifigyuri/Projects/projs/ui/vendor/bundle/ruby/2.2.0/gems/guard-2.10.5/lib/guard/ui.rb:186:in `_filtered_logger_message'
        from /Users/fifigyuri/Projects/projs/ui/vendor/bundle/ruby/2.2.0/gems/guard-2.10.5/lib/guard/ui.rb:90:in `error'
        from /Users/fifigyuri/Projects/projs/ui/vendor/bundle/ruby/2.2.0/bundler/gems/guard-jasmine-9728620cec1d/lib/guard/jasmine/cli.rb:234:in `rescue in spec'
        from /Users/fifigyuri/Projects/projs/ui/vendor/bundle/ruby/2.2.0/bundler/gems/guard-jasmine-9728620cec1d/lib/guard/jasmine/cli.rb:176:in `spec'
        from /Users/fifigyuri/Projects/projs/ui/vendor/bundle/ruby/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /Users/fifigyuri/Projects/projs/ui/vendor/bundle/ruby/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /Users/fifigyuri/Projects/projs/ui/vendor/bundle/ruby/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /Users/fifigyuri/Projects/projs/ui/vendor/bundle/ruby/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /Users/fifigyuri/Projects/projs/ui/vendor/bundle/ruby/2.2.0/bundler/gems/guard-jasmine-9728620cec1d/bin/guard-jasmine:3:in `<top (required)>'
        from /Users/fifigyuri/Projects/projs/ui/vendor/bundle/ruby/2.2.0/bin/guard-jasmine:23:in `load'
        from /Users/fifigyuri/Projects/projs/ui/vendor/bundle/ruby/2.2.0/bin/guard-jasmine:23:in `<main>'
```

When I added `gem 'guard', github: 'guard'` to the `Gemfile`, it changed to:

```
/Users/fifigyuri/Projects/projs/ui/vendor/bundle/ruby/2.2.0/bundler/gems/guard-f28ec8b86b9d/lib/guard/ui.rb:40:in `options': uninitialized constant Module::Options (NameError)
        from /Users/fifigyuri/Projects/projs/ui/vendor/bundle/ruby/2.2.0/bundler/gems/guard-f28ec8b86b9d/lib/guard/ui.rb:171:in `_filter'
        from /Users/fifigyuri/Projects/projs/ui/vendor/bundle/ruby/2.2.0/bundler/gems/guard-f28ec8b86b9d/lib/guard/ui.rb:186:in `_filtered_logger_message'
        from /Users/fifigyuri/Projects/projs/ui/vendor/bundle/ruby/2.2.0/bundler/gems/guard-f28ec8b86b9d/lib/guard/ui.rb:90:in `error'
        from /Users/fifigyuri/Projects/projs/ui/vendor/bundle/ruby/2.2.0/bundler/gems/guard-jasmine-9728620cec1d/lib/guard/jasmine/cli.rb:234:in `rescue in spec'
        from /Users/fifigyuri/Projects/projs/ui/vendor/bundle/ruby/2.2.0/bundler/gems/guard-jasmine-9728620cec1d/lib/guard/jasmine/cli.rb:176:in `spec'
        from /Users/fifigyuri/Projects/projs/ui/vendor/bundle/ruby/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /Users/fifigyuri/Projects/projs/ui/vendor/bundle/ruby/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `projs/ui/vendor/bundle/ruby/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /Users/fifigyuri/Projects/projs/ui/vendor/bundle/ruby/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /Users/fifigyuri/Projects/projs/ui/vendor/bundle/ruby/2.2.0/bundler/gems/guard-jasmine-9728620cec1d/bin/guard-jasmine:3:in `<top (required)>'
        from /Users/fifigyuri/Projects/projs/ui/vendor/bundle/ruby/2.2.0/bin/guard-jasmine:23:in `load'
        from /Users/fifigyuri/Projects/projs/ui/vendor/bundle/ruby/2.2.0/bin/guard-jasmine:23:in `<main>'
```

Thank you for your help.

**Comment by e2** [comment]
Should be fixed in Guard 2.11.0.

Thanks and let me know if you have any other issues!
