### ISSUE TITLE
Runner error: Timeout waiting for the Jasmine test results!

### ISSUE THREAD

**Issue by JustinAiken** [guard/guard-jasmine#184]
Using guard-jasmine from github master (4dfd352c0b9f0023dbd5870ff43b36e3afa84981):

If I open the jasmine URL in my browser it works fine.

```bash
$ bundle exec rake guard:jspec

12:23:16 - INFO - Guard::Jasmine starts webrick spec server on port 64245 in test environment (coverage off).
12:23:21 - INFO - Waiting for Jasmine test runner at http://localhost:64245/jasmine
12:23:21 - INFO - Run all Jasmine suites
12:24:23 - ERROR - Something went wrong: Runner error: Timeout waiting for the Jasmine test results!
> [#]
> [#] Jasmine 1.3.1 revision 1354556913finished in 0.075s
> [#] No try/catch
> [#] Passing 52 specs
...
snip - title of all my tests
...

12:24:23 - INFO - Guard::Jasmine stops server.
rake aborted!
The spec couldn't be run: exit'
/Users/jaiken/.rvm/gems/ruby-2.1.1/bundler/gems/guard-jasmine-4dfd352c0b9f/lib/guard/jasmine/task.rb:42:in `rescue in block (2 levels) in initialize'
/Users/jaiken/.rvm/gems/ruby-2.1.1/bundler/gems/guard-jasmine-4dfd352c0b9f/lib/guard/jasmine/task.rb:34:in `block (2 levels) in initialize'
/Users/jaiken/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `eval'
/Users/jaiken/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `<main>'
SystemExit: exit
/Users/jaiken/.rvm/gems/ruby-2.1.1/bundler/gems/guard-jasmine-4dfd352c0b9f/lib/guard/jasmine/cli.rb:229:in `exit'
/Users/jaiken/.rvm/gems/ruby-2.1.1/bundler/gems/guard-jasmine-4dfd352c0b9f/lib/guard/jasmine/cli.rb:229:in `rescue in spec'
/Users/jaiken/.rvm/gems/ruby-2.1.1/bundler/gems/guard-jasmine-4dfd352c0b9f/lib/guard/jasmine/cli.rb:232:in `spec'
/Users/jaiken/.rvm/gems/ruby-2.1.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
/Users/jaiken/.rvm/gems/ruby-2.1.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
/Users/jaiken/.rvm/gems/ruby-2.1.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
/Users/jaiken/.rvm/gems/ruby-2.1.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
/Users/jaiken/.rvm/gems/ruby-2.1.1/bundler/gems/guard-jasmine-4dfd352c0b9f/lib/guard/jasmine/task.rb:35:in `block (2 levels) in initialize'
/Users/jaiken/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `eval'
/Users/jaiken/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `<main>'
Runner error: Timeout waiting for the Jasmine test results!

Jasmine 1.3.1 revision 1354556913finished in 0.075s
No try/catch
Passing 52 specs
....
snip - title of all my tests
....

should define $
$ should equal jQuery
should define _
should define Backbone/Users/jaiken/.rvm/gems/ruby-2.1.1/bundler/gems/guard-jasmine-4dfd352c0b9f/lib/guard/jasmine/runner.rb:245:in `evaluate_response'
/Users/jaiken/.rvm/gems/ruby-2.1.1/bundler/gems/guard-jasmine-4dfd352c0b9f/lib/guard/jasmine/runner.rb:57:in `block in run'
/Users/jaiken/.rvm/gems/ruby-2.1.1/bundler/gems/guard-jasmine-4dfd352c0b9f/lib/guard/jasmine/runner.rb:55:in `each'
/Users/jaiken/.rvm/gems/ruby-2.1.1/bundler/gems/guard-jasmine-4dfd352c0b9f/lib/guard/jasmine/runner.rb:55:in `each_with_object'
/Users/jaiken/.rvm/gems/ruby-2.1.1/bundler/gems/guard-jasmine-4dfd352c0b9f/lib/guard/jasmine/runner.rb:55:in `run'
/Users/jaiken/.rvm/gems/ruby-2.1.1/bundler/gems/guard-jasmine-4dfd352c0b9f/lib/guard/jasmine/cli.rb:216:in `spec'
/Users/jaiken/.rvm/gems/ruby-2.1.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
/Users/jaiken/.rvm/gems/ruby-2.1.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
/Users/jaiken/.rvm/gems/ruby-2.1.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
/Users/jaiken/.rvm/gems/ruby-2.1.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
/Users/jaiken/.rvm/gems/ruby-2.1.1/bundler/gems/guard-jasmine-4dfd352c0b9f/lib/guard/jasmine/task.rb:35:in `block (2 levels) in initialize'
/Users/jaiken/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `eval'
/Users/jaiken/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => guard:jspec
(See full trace by running task with --trace)

```

**Comment by nathanstitt** [comment]
Interesting, a timeout while it was waiting for results.  I don't think I've encountered that one yet. Usually if it times out, it's while starting up.

A possibility might be multiple specs that use the jasmine "done" function to signal completion, and they're not calling done(), which would make them take quite awhile to execute.  Or it could just be a bug in guard-jasmine as well.

Are you able to execute the specs from a browser?  You should be able to do so by visiting the url given when it starts up, for the example you gave it was: http://localhost:64245/jasmine  The port number will change between runs though, so that probably won't be the same.

**Comment by JustinAiken** [comment]
Yes, opening the url has all the tests passing green.

**Comment by nathanstitt** [comment]
ok, perhaps it's a parsing error with the reply then.  Can you put guard-jasmine in debug mode and re-run it?  You can do so by setting debug: true in the guard options - something like:

    guard :jasmine, debug:true do
        watch(%r{^spec/javascripts/.*(?:_s|S)pec\.(coffee|js)$})
    end

That should print out all of the replies that guard-jasmine receives.  If you could paste that in here, hopefully I can spot something amiss.

**Comment by JustinAiken** [comment]
Running `rake guard:jspec` doesn't seem to make a difference with the `:debug` option in the Guardfile..

If I start guard, and type `jasmine` to run it, I get:

```ruby
1] guard(main)> jasmine
13:29:56 - INFO - Run Jasmine
13:29:56 - INFO - Run all Jasmine suites
/usr/local/bin/phantomjs /Users/jaiken/.rvm/gems/ruby-2.1.1/bundler/gems/guard-jasmine-4dfd352c0b9f/lib/guard/jasmine/phantomjs/guard-jasmine.js "http://localhost:49700/jasmine" 60000 failure true failure failure false true ''
{"error"=>
  "Timeout waiting for the Jasmine test results!\n\nJasmine 1.3.1 revision 1354556913finished in 0.066s\nNo try/catch\nPassing 52 specs\n ---snip: all my tests ----"}
13:31:02 - ERROR - An error occurred: Timeout waiting for the Jasmine test results!
> [#623FF95989B8]
> [#623FF95989B8] Jasmine 1.3.1 revision 1354556913finished in 0.066s
> [#623FF95989B8] No try/catch
> [#623FF95989B8] Passing 52 specs
...
snip -- all my tests
...
```

**Comment by nathanstitt** [comment]
ah, actually that does provide me a bit more info.  That error's coming from the test runner itself so the communication between the two is functioning properly.  Looks like it did have a timeout though.

Can you give me a rough idea how long it takes to run all the specs from the browser?  Maybe it's just a case of you've got a lot of slow specs and I should bump up the timeout.  Or at least make it configurable.

**Comment by JustinAiken** [comment]
> Maybe it's just a case of you've got a lot of slow specs and I should bump up the timeout

Nah the specs are near instant - that `0.066s` is about right; well under a second.

**Comment by nathanstitt** [comment]
Circling back to this - I think I'll add some more debugging to the Jasmine runner this weekend and ask you to try the new version in hopes it'll help pinpoint where it's failing

**Comment by nathanstitt** [comment]
Hey @JustinAiken - I've just released a new version 2.0.3, which encloses the timeout in a try/catch block so it can report on any errors it encounters. 

Please give the new version a try and let me know if it helps your issue.

**Comment by JustinAiken** [comment]
Cool, I'll give a try tomorrow... thanks!

**Comment by nathanstitt** [comment]
I'm pruning old issues.  I'm hoping the new version worked for you, please let me know if it's not.
